export type CenterMeta = {
  slug: string
  city: string
  state: string
  stateAbbr: string
  waitWeeks: string
  centers: number
  population: string
  landmark: string
  releaseDate: string  // YYYY-MM-DD — pages only built if releaseDate <= today
}

export const SERVICE_CENTERS: CenterMeta[] = [
  // ── Tier 1: Major metros ──────────────────────────────────────────────────
  {
    slug: 'los-angeles-tesla-service',
    city: 'Los Angeles',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '5–8',
    centers: 5,
    population: '3.9M',
    landmark: 'Greater LA',
    releaseDate: '2026-06-30',
  },
  {
    slug: 'san-francisco-tesla-service',
    city: 'San Francisco',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '4–6',
    centers: 3,
    population: '870,000',
    landmark: 'Bay Area',
    releaseDate: '2026-06-30',
  },
  {
    slug: 'new-york-tesla-service',
    city: 'New York',
    state: 'New York',
    stateAbbr: 'NY',
    waitWeeks: '6–10',
    centers: 4,
    population: '8.3M',
    landmark: 'NYC metro',
    releaseDate: '2026-06-30',
  },
  {
    slug: 'chicago-tesla-service',
    city: 'Chicago',
    state: 'Illinois',
    stateAbbr: 'IL',
    waitWeeks: '3–5',
    centers: 2,
    population: '2.7M',
    landmark: 'Chicagoland',
    releaseDate: '2026-06-30',
  },
  {
    slug: 'seattle-tesla-service',
    city: 'Seattle',
    state: 'Washington',
    stateAbbr: 'WA',
    waitWeeks: '4–7',
    centers: 3,
    population: '750,000',
    landmark: 'Puget Sound',
    releaseDate: '2026-06-30',
  },
  {
    slug: 'dallas-tesla-service',
    city: 'Dallas',
    state: 'Texas',
    stateAbbr: 'TX',
    waitWeeks: '3–5',
    centers: 3,
    population: '1.3M',
    landmark: 'DFW metro',
    releaseDate: '2026-07-07',
  },
  {
    slug: 'houston-tesla-service',
    city: 'Houston',
    state: 'Texas',
    stateAbbr: 'TX',
    waitWeeks: '3–5',
    centers: 3,
    population: '2.3M',
    landmark: 'Greater Houston',
    releaseDate: '2026-07-07',
  },
  {
    slug: 'miami-tesla-service',
    city: 'Miami',
    state: 'Florida',
    stateAbbr: 'FL',
    waitWeeks: '3–6',
    centers: 3,
    population: '440,000',
    landmark: 'South Florida',
    releaseDate: '2026-06-30',
  },
  {
    slug: 'boston-tesla-service',
    city: 'Boston',
    state: 'Massachusetts',
    stateAbbr: 'MA',
    waitWeeks: '4–7',
    centers: 2,
    population: '680,000',
    landmark: 'Greater Boston',
    releaseDate: '2026-06-30',
  },
  {
    slug: 'washington-dc-tesla-service',
    city: 'Washington DC',
    state: 'District of Columbia',
    stateAbbr: 'DC',
    waitWeeks: '4–6',
    centers: 3,
    population: '700,000',
    landmark: 'DMV area',
    releaseDate: '2026-06-30',
  },
  {
    slug: 'atlanta-tesla-service',
    city: 'Atlanta',
    state: 'Georgia',
    stateAbbr: 'GA',
    waitWeeks: '4–6',
    centers: 2,
    population: '500,000',
    landmark: 'Metro Atlanta',
    releaseDate: '2026-06-30',
  },
  {
    slug: 'denver-tesla-service',
    city: 'Denver',
    state: 'Colorado',
    stateAbbr: 'CO',
    waitWeeks: '3–5',
    centers: 2,
    population: '730,000',
    landmark: 'Front Range',
    releaseDate: '2026-06-30',
  },
  {
    slug: 'phoenix-tesla-service',
    city: 'Phoenix',
    state: 'Arizona',
    stateAbbr: 'AZ',
    waitWeeks: '2–4',
    centers: 3,
    population: '1.6M',
    landmark: 'Valley of the Sun',
    releaseDate: '2026-06-30',
  },
  {
    slug: 'portland-tesla-service',
    city: 'Portland',
    state: 'Oregon',
    stateAbbr: 'OR',
    waitWeeks: '3–5',
    centers: 2,
    population: '650,000',
    landmark: 'Portland metro',
    releaseDate: '2026-06-30',
  },
  {
    slug: 'san-diego-tesla-service',
    city: 'San Diego',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '3–5',
    centers: 2,
    population: '1.4M',
    landmark: 'San Diego County',
    releaseDate: '2026-06-30',
  },
  {
    slug: 'las-vegas-tesla-service',
    city: 'Las Vegas',
    state: 'Nevada',
    stateAbbr: 'NV',
    waitWeeks: '2–4',
    centers: 2,
    population: '640,000',
    landmark: 'Las Vegas Valley',
    releaseDate: '2026-07-07',
  },
  {
    slug: 'minneapolis-tesla-service',
    city: 'Minneapolis',
    state: 'Minnesota',
    stateAbbr: 'MN',
    waitWeeks: '3–5',
    centers: 2,
    population: '430,000',
    landmark: 'Twin Cities',
    releaseDate: '2026-07-07',
  },
  {
    slug: 'detroit-tesla-service',
    city: 'Detroit',
    state: 'Michigan',
    stateAbbr: 'MI',
    waitWeeks: '3–5',
    centers: 2,
    population: '670,000',
    landmark: 'Metro Detroit',
    releaseDate: '2026-07-07',
  },
  {
    slug: 'philadelphia-tesla-service',
    city: 'Philadelphia',
    state: 'Pennsylvania',
    stateAbbr: 'PA',
    waitWeeks: '4–6',
    centers: 2,
    population: '1.6M',
    landmark: 'Greater Philadelphia',
    releaseDate: '2026-07-07',
  },
  {
    slug: 'san-jose-tesla-service',
    city: 'San Jose',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '4–6',
    centers: 2,
    population: '1.0M',
    landmark: 'Silicon Valley',
    releaseDate: '2026-06-30',
  },
  {
    slug: 'austin-tesla-service',
    city: 'Austin',
    state: 'Texas',
    stateAbbr: 'TX',
    waitWeeks: '2–4',
    centers: 2,
    population: '980,000',
    landmark: 'Central Texas',
    releaseDate: '2026-06-30',
  },
  {
    slug: 'nashville-tesla-service',
    city: 'Nashville',
    state: 'Tennessee',
    stateAbbr: 'TN',
    waitWeeks: '3–5',
    centers: 1,
    population: '690,000',
    landmark: 'Middle Tennessee',
    releaseDate: '2026-07-07',
  },
  {
    slug: 'charlotte-tesla-service',
    city: 'Charlotte',
    state: 'North Carolina',
    stateAbbr: 'NC',
    waitWeeks: '3–6',
    centers: 1,
    population: '900,000',
    landmark: 'Greater Charlotte',
    releaseDate: '2026-07-07',
  },
  {
    slug: 'tampa-tesla-service',
    city: 'Tampa',
    state: 'Florida',
    stateAbbr: 'FL',
    waitWeeks: '3–5',
    centers: 2,
    population: '400,000',
    landmark: 'Tampa Bay area',
    releaseDate: '2026-11-01',
  },
  {
    slug: 'orlando-tesla-service',
    city: 'Orlando',
    state: 'Florida',
    stateAbbr: 'FL',
    waitWeeks: '3–5',
    centers: 2,
    population: '310,000',
    landmark: 'Central Florida',
    releaseDate: '2026-11-01',
  },

  // ── Tier 2: Mid-size markets ──────────────────────────────────────────────
  {
    slug: 'salt-lake-city-tesla-service',
    city: 'Salt Lake City',
    state: 'Utah',
    stateAbbr: 'UT',
    waitWeeks: '2–3',
    centers: 1,
    population: '210,000',
    landmark: 'Wasatch Front',
    releaseDate: '2026-07-07',
  },
  {
    slug: 'sacramento-tesla-service',
    city: 'Sacramento',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '3–5',
    centers: 2,
    population: '530,000',
    landmark: 'Greater Sacramento',
    releaseDate: '2026-07-21',
  },
  {
    slug: 'san-antonio-tesla-service',
    city: 'San Antonio',
    state: 'Texas',
    stateAbbr: 'TX',
    waitWeeks: '2–4',
    centers: 1,
    population: '1.4M',
    landmark: 'San Antonio metro',
    releaseDate: '2026-07-21',
  },
  {
    slug: 'kansas-city-tesla-service',
    city: 'Kansas City',
    state: 'Missouri',
    stateAbbr: 'MO',
    waitWeeks: '2–4',
    centers: 1,
    population: '500,000',
    landmark: 'KC metro',
    releaseDate: '2026-07-21',
  },
  {
    slug: 'columbus-tesla-service',
    city: 'Columbus',
    state: 'Ohio',
    stateAbbr: 'OH',
    waitWeeks: '3–5',
    centers: 1,
    population: '910,000',
    landmark: 'Central Ohio',
    releaseDate: '2026-07-21',
  },
  {
    slug: 'indianapolis-tesla-service',
    city: 'Indianapolis',
    state: 'Indiana',
    stateAbbr: 'IN',
    waitWeeks: '3–5',
    centers: 1,
    population: '870,000',
    landmark: 'Indy metro',
    releaseDate: '2026-07-21',
  },
  {
    slug: 'raleigh-tesla-service',
    city: 'Raleigh',
    state: 'North Carolina',
    stateAbbr: 'NC',
    waitWeeks: '3–5',
    centers: 1,
    population: '470,000',
    landmark: 'Research Triangle',
    releaseDate: '2026-07-07',
  },
  {
    slug: 'richmond-tesla-service',
    city: 'Richmond',
    state: 'Virginia',
    stateAbbr: 'VA',
    waitWeeks: '3–5',
    centers: 1,
    population: '230,000',
    landmark: 'Greater Richmond',
    releaseDate: '2026-11-01',
  },
  {
    slug: 'memphis-tesla-service',
    city: 'Memphis',
    state: 'Tennessee',
    stateAbbr: 'TN',
    waitWeeks: '3–6',
    centers: 1,
    population: '630,000',
    landmark: 'Memphis metro',
    releaseDate: '2026-07-21',
  },
  {
    slug: 'louisville-tesla-service',
    city: 'Louisville',
    state: 'Kentucky',
    stateAbbr: 'KY',
    waitWeeks: '3–5',
    centers: 1,
    population: '640,000',
    landmark: 'Louisville metro',
    releaseDate: '2026-07-21',
  },
  {
    slug: 'new-orleans-tesla-service',
    city: 'New Orleans',
    state: 'Louisiana',
    stateAbbr: 'LA',
    waitWeeks: '3–6',
    centers: 1,
    population: '380,000',
    landmark: 'Greater New Orleans',
    releaseDate: '2026-07-21',
  },
  {
    slug: 'oklahoma-city-tesla-service',
    city: 'Oklahoma City',
    state: 'Oklahoma',
    stateAbbr: 'OK',
    waitWeeks: '2–4',
    centers: 1,
    population: '680,000',
    landmark: 'OKC metro',
    releaseDate: '2026-10-15',
  },
  {
    slug: 'tulsa-tesla-service',
    city: 'Tulsa',
    state: 'Oklahoma',
    stateAbbr: 'OK',
    waitWeeks: '2–4',
    centers: 1,
    population: '410,000',
    landmark: 'Tulsa metro',
    releaseDate: '2026-10-15',
  },
  {
    slug: 'albuquerque-tesla-service',
    city: 'Albuquerque',
    state: 'New Mexico',
    stateAbbr: 'NM',
    waitWeeks: '3–5',
    centers: 1,
    population: '560,000',
    landmark: 'Albuquerque metro',
    releaseDate: '2026-10-15',
  },
  {
    slug: 'tucson-tesla-service',
    city: 'Tucson',
    state: 'Arizona',
    stateAbbr: 'AZ',
    waitWeeks: '2–4',
    centers: 1,
    population: '550,000',
    landmark: 'Greater Tucson',
    releaseDate: '2026-10-15',
  },
  {
    slug: 'fresno-tesla-service',
    city: 'Fresno',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '3–5',
    centers: 1,
    population: '540,000',
    landmark: 'Central Valley',
    releaseDate: '2026-07-21',
  },
  {
    slug: 'bakersfield-tesla-service',
    city: 'Bakersfield',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '3–5',
    centers: 1,
    population: '400,000',
    landmark: 'Kern County',
    releaseDate: '2026-07-21',
  },
  {
    slug: 'riverside-tesla-service',
    city: 'Riverside',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '3–5',
    centers: 1,
    population: '330,000',
    landmark: 'Inland Empire',
    releaseDate: '2026-07-07',
  },
  {
    slug: 'long-beach-tesla-service',
    city: 'Long Beach',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '4–7',
    centers: 1,
    population: '460,000',
    landmark: 'South Bay LA',
    releaseDate: '2026-07-14',
  },
  {
    slug: 'anaheim-tesla-service',
    city: 'Anaheim',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '4–6',
    centers: 1,
    population: '350,000',
    landmark: 'Orange County',
    releaseDate: '2026-07-07',
  },
  {
    slug: 'santa-ana-tesla-service',
    city: 'Santa Ana',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '4–6',
    centers: 1,
    population: '310,000',
    landmark: 'Orange County',
    releaseDate: '2026-07-14',
  },
  {
    slug: 'corpus-christi-tesla-service',
    city: 'Corpus Christi',
    state: 'Texas',
    stateAbbr: 'TX',
    waitWeeks: '2–4',
    centers: 1,
    population: '320,000',
    landmark: 'Coastal Bend',
    releaseDate: '2026-10-15',
  },
  {
    slug: 'colorado-springs-tesla-service',
    city: 'Colorado Springs',
    state: 'Colorado',
    stateAbbr: 'CO',
    waitWeeks: '2–4',
    centers: 1,
    population: '480,000',
    landmark: 'Pikes Peak region',
    releaseDate: '2026-08-04',
  },
  {
    slug: 'aurora-tesla-service',
    city: 'Aurora',
    state: 'Colorado',
    stateAbbr: 'CO',
    waitWeeks: '3–5',
    centers: 1,
    population: '380,000',
    landmark: 'Front Range',
    releaseDate: '2026-08-11',
  },
  {
    slug: 'henderson-tesla-service',
    city: 'Henderson',
    state: 'Nevada',
    stateAbbr: 'NV',
    waitWeeks: '2–4',
    centers: 1,
    population: '320,000',
    landmark: 'Las Vegas Valley',
    releaseDate: '2026-08-11',
  },
  {
    slug: 'north-las-vegas-tesla-service',
    city: 'North Las Vegas',
    state: 'Nevada',
    stateAbbr: 'NV',
    waitWeeks: '2–4',
    centers: 1,
    population: '265,000',
    landmark: 'Las Vegas Valley',
    releaseDate: '2026-10-15',
  },

  // ── Tier 3: Regional ─────────────────────────────────────────────────────
  {
    slug: 'boise-tesla-service',
    city: 'Boise',
    state: 'Idaho',
    stateAbbr: 'ID',
    waitWeeks: '2–4',
    centers: 1,
    population: '240,000',
    landmark: 'Treasure Valley',
    releaseDate: '2026-08-04',
  },
  {
    slug: 'spokane-tesla-service',
    city: 'Spokane',
    state: 'Washington',
    stateAbbr: 'WA',
    waitWeeks: '3–5',
    centers: 1,
    population: '220,000',
    landmark: 'Eastern Washington',
    releaseDate: '2026-08-04',
  },
  {
    slug: 'tacoma-tesla-service',
    city: 'Tacoma',
    state: 'Washington',
    stateAbbr: 'WA',
    waitWeeks: '4–6',
    centers: 1,
    population: '220,000',
    landmark: 'South Puget Sound',
    releaseDate: '2026-08-04',
  },
  {
    slug: 'bellevue-tesla-service',
    city: 'Bellevue',
    state: 'Washington',
    stateAbbr: 'WA',
    waitWeeks: '4–7',
    centers: 1,
    population: '145,000',
    landmark: 'Eastside Seattle',
    releaseDate: '2026-07-14',
  },
  {
    slug: 'redmond-tesla-service',
    city: 'Redmond',
    state: 'Washington',
    stateAbbr: 'WA',
    waitWeeks: '4–7',
    centers: 1,
    population: '70,000',
    landmark: 'Eastside Seattle',
    releaseDate: '2026-11-01',
  },
  {
    slug: 'fremont-tesla-service',
    city: 'Fremont',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '4–6',
    centers: 1,
    population: '240,000',
    landmark: 'East Bay',
    releaseDate: '2026-07-14',
  },
  {
    slug: 'san-mateo-tesla-service',
    city: 'San Mateo',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '4–6',
    centers: 1,
    population: '105,000',
    landmark: 'Peninsula',
    releaseDate: '2026-07-14',
  },
  {
    slug: 'palo-alto-tesla-service',
    city: 'Palo Alto',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '4–6',
    centers: 1,
    population: '68,000',
    landmark: 'Silicon Valley',
    releaseDate: '2026-07-14',
  },
  {
    slug: 'santa-clara-tesla-service',
    city: 'Santa Clara',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '4–6',
    centers: 1,
    population: '130,000',
    landmark: 'Silicon Valley',
    releaseDate: '2026-07-14',
  },
  {
    slug: 'sunnyvale-tesla-service',
    city: 'Sunnyvale',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '4–6',
    centers: 1,
    population: '155,000',
    landmark: 'Silicon Valley',
    releaseDate: '2026-07-14',
  },
  {
    slug: 'mountain-view-tesla-service',
    city: 'Mountain View',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '4–6',
    centers: 1,
    population: '82,000',
    landmark: 'Silicon Valley',
    releaseDate: '2026-07-14',
  },
  {
    slug: 'redwood-city-tesla-service',
    city: 'Redwood City',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '4–6',
    centers: 1,
    population: '85,000',
    landmark: 'Peninsula',
    releaseDate: '2026-07-14',
  },
  {
    slug: 'burlingame-tesla-service',
    city: 'Burlingame',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '4–6',
    centers: 1,
    population: '32,000',
    landmark: 'Peninsula',
    releaseDate: '2026-07-14',
  },
  {
    slug: 'san-ramon-tesla-service',
    city: 'San Ramon',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '3–5',
    centers: 1,
    population: '84,000',
    landmark: 'East Bay',
    releaseDate: '2026-08-11',
  },
  {
    slug: 'pleasanton-tesla-service',
    city: 'Pleasanton',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '3–5',
    centers: 1,
    population: '82,000',
    landmark: 'Tri-Valley',
    releaseDate: '2026-08-11',
  },
  {
    slug: 'walnut-creek-tesla-service',
    city: 'Walnut Creek',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '4–6',
    centers: 1,
    population: '70,000',
    landmark: 'East Bay',
    releaseDate: '2026-08-11',
  },
  {
    slug: 'concord-tesla-service',
    city: 'Concord',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '4–6',
    centers: 1,
    population: '130,000',
    landmark: 'East Bay',
    releaseDate: '2026-08-11',
  },
  {
    slug: 'oakland-tesla-service',
    city: 'Oakland',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '4–7',
    centers: 1,
    population: '430,000',
    landmark: 'East Bay',
    releaseDate: '2026-07-28',
  },
  {
    slug: 'berkeley-tesla-service',
    city: 'Berkeley',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '4–7',
    centers: 1,
    population: '120,000',
    landmark: 'East Bay',
    releaseDate: '2026-07-28',
  },
  {
    slug: 'santa-rosa-tesla-service',
    city: 'Santa Rosa',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '3–5',
    centers: 1,
    population: '175,000',
    landmark: 'Wine Country',
    releaseDate: '2026-07-28',
  },
  {
    slug: 'ventura-tesla-service',
    city: 'Ventura',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '4–6',
    centers: 1,
    population: '110,000',
    landmark: 'Ventura County',
    releaseDate: '2026-07-28',
  },
  {
    slug: 'oxnard-tesla-service',
    city: 'Oxnard',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '4–6',
    centers: 1,
    population: '210,000',
    landmark: 'Ventura County',
    releaseDate: '2026-07-28',
  },
  {
    slug: 'thousand-oaks-tesla-service',
    city: 'Thousand Oaks',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '4–6',
    centers: 1,
    population: '128,000',
    landmark: 'Conejo Valley',
    releaseDate: '2026-07-28',
  },
  {
    slug: 'pasadena-tesla-service',
    city: 'Pasadena',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '4–7',
    centers: 1,
    population: '140,000',
    landmark: 'San Gabriel Valley',
    releaseDate: '2026-07-14',
  },
  {
    slug: 'pomona-tesla-service',
    city: 'Pomona',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '4–6',
    centers: 1,
    population: '150,000',
    landmark: 'Inland Valley',
    releaseDate: '2026-07-28',
  },
  {
    slug: 'ontario-tesla-service',
    city: 'Ontario',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '4–6',
    centers: 1,
    population: '180,000',
    landmark: 'Inland Empire',
    releaseDate: '2026-07-28',
  },
  {
    slug: 'fontana-tesla-service',
    city: 'Fontana',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '4–6',
    centers: 1,
    population: '215,000',
    landmark: 'Inland Empire',
    releaseDate: '2026-07-28',
  },
  {
    slug: 'rancho-cucamonga-tesla-service',
    city: 'Rancho Cucamonga',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '4–6',
    centers: 1,
    population: '175,000',
    landmark: 'Inland Empire',
    releaseDate: '2026-07-28',
  },
  {
    slug: 'corona-tesla-service',
    city: 'Corona',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '4–6',
    centers: 1,
    population: '168,000',
    landmark: 'Inland Empire',
    releaseDate: '2026-07-28',
  },
  {
    slug: 'moreno-valley-tesla-service',
    city: 'Moreno Valley',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '4–6',
    centers: 1,
    population: '210,000',
    landmark: 'Inland Empire',
    releaseDate: '2026-07-28',
  },
  {
    slug: 'escondido-tesla-service',
    city: 'Escondido',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '3–5',
    centers: 1,
    population: '152,000',
    landmark: 'North San Diego County',
    releaseDate: '2026-08-04',
  },
  {
    slug: 'chula-vista-tesla-service',
    city: 'Chula Vista',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '3–5',
    centers: 1,
    population: '270,000',
    landmark: 'South Bay San Diego',
    releaseDate: '2026-08-04',
  },
  {
    slug: 'el-cajon-tesla-service',
    city: 'El Cajon',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '3–5',
    centers: 1,
    population: '103,000',
    landmark: 'East San Diego County',
    releaseDate: '2026-08-04',
  },
  {
    slug: 'oceanside-tesla-service',
    city: 'Oceanside',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '3–5',
    centers: 1,
    population: '175,000',
    landmark: 'North San Diego County',
    releaseDate: '2026-08-04',
  },
  {
    slug: 'murrieta-tesla-service',
    city: 'Murrieta',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '3–5',
    centers: 1,
    population: '120,000',
    landmark: 'Southwest Riverside County',
    releaseDate: '2026-08-04',
  },
  {
    slug: 'temecula-tesla-service',
    city: 'Temecula',
    state: 'California',
    stateAbbr: 'CA',
    waitWeeks: '3–5',
    centers: 1,
    population: '112,000',
    landmark: 'Wine Country',
    releaseDate: '2026-08-04',
  },

  // ── Northeast / Mid-Atlantic ──────────────────────────────────────────────
  {
    slug: 'greenwich-ct-tesla-service',
    city: 'Greenwich',
    state: 'Connecticut',
    stateAbbr: 'CT',
    waitWeeks: '4–7',
    centers: 1,
    population: '63,000',
    landmark: 'Fairfield County',
    releaseDate: '2026-08-11',
  },
  {
    slug: 'white-plains-ny-tesla-service',
    city: 'White Plains',
    state: 'New York',
    stateAbbr: 'NY',
    waitWeeks: '4–7',
    centers: 1,
    population: '58,000',
    landmark: 'Westchester County',
    releaseDate: '2026-08-11',
  },
  {
    slug: 'paramus-nj-tesla-service',
    city: 'Paramus',
    state: 'New Jersey',
    stateAbbr: 'NJ',
    waitWeeks: '4–7',
    centers: 1,
    population: '26,000',
    landmark: 'Bergen County NJ',
    releaseDate: '2026-08-18',
  },
  {
    slug: 'cherry-hill-nj-tesla-service',
    city: 'Cherry Hill',
    state: 'New Jersey',
    stateAbbr: 'NJ',
    waitWeeks: '4–6',
    centers: 1,
    population: '71,000',
    landmark: 'South Jersey',
    releaseDate: '2026-08-18',
  },
  {
    slug: 'rockville-md-tesla-service',
    city: 'Rockville',
    state: 'Maryland',
    stateAbbr: 'MD',
    waitWeeks: '4–6',
    centers: 1,
    population: '68,000',
    landmark: 'Montgomery County MD',
    releaseDate: '2026-08-18',
  },
  {
    slug: 'tyson-va-tesla-service',
    city: 'Tysons',
    state: 'Virginia',
    stateAbbr: 'VA',
    waitWeeks: '4–6',
    centers: 1,
    population: '23,000',
    landmark: 'Northern Virginia',
    releaseDate: '2026-08-18',
  },
  {
    slug: 'fairfax-va-tesla-service',
    city: 'Fairfax',
    state: 'Virginia',
    stateAbbr: 'VA',
    waitWeeks: '4–6',
    centers: 1,
    population: '24,000',
    landmark: 'Northern Virginia',
    releaseDate: '2026-08-18',
  },
  {
    slug: 'bethesda-md-tesla-service',
    city: 'Bethesda',
    state: 'Maryland',
    stateAbbr: 'MD',
    waitWeeks: '4–6',
    centers: 1,
    population: '65,000',
    landmark: 'Montgomery County MD',
    releaseDate: '2026-08-18',
  },
  {
    slug: 'annapolis-md-tesla-service',
    city: 'Annapolis',
    state: 'Maryland',
    stateAbbr: 'MD',
    waitWeeks: '3–5',
    centers: 1,
    population: '40,000',
    landmark: 'Anne Arundel County',
    releaseDate: '2026-08-18',
  },
  {
    slug: 'towson-md-tesla-service',
    city: 'Towson',
    state: 'Maryland',
    stateAbbr: 'MD',
    waitWeeks: '3–5',
    centers: 1,
    population: '55,000',
    landmark: 'Baltimore County',
    releaseDate: '2026-08-18',
  },
  {
    slug: 'wilmington-de-tesla-service',
    city: 'Wilmington',
    state: 'Delaware',
    stateAbbr: 'DE',
    waitWeeks: '3–5',
    centers: 1,
    population: '70,000',
    landmark: 'Northern Delaware',
    releaseDate: '2026-10-15',
  },
  {
    slug: 'princeton-nj-tesla-service',
    city: 'Princeton',
    state: 'New Jersey',
    stateAbbr: 'NJ',
    waitWeeks: '4–6',
    centers: 1,
    population: '30,000',
    landmark: 'Central New Jersey',
    releaseDate: '2026-08-18',
  },
  {
    slug: 'stamford-ct-tesla-service',
    city: 'Stamford',
    state: 'Connecticut',
    stateAbbr: 'CT',
    waitWeeks: '4–7',
    centers: 1,
    population: '135,000',
    landmark: 'Fairfield County',
    releaseDate: '2026-08-11',
  },
  {
    slug: 'hartford-ct-tesla-service',
    city: 'Hartford',
    state: 'Connecticut',
    stateAbbr: 'CT',
    waitWeeks: '3–5',
    centers: 1,
    population: '121,000',
    landmark: 'Greater Hartford',
    releaseDate: '2026-08-18',
  },
  {
    slug: 'providence-ri-tesla-service',
    city: 'Providence',
    state: 'Rhode Island',
    stateAbbr: 'RI',
    waitWeeks: '3–6',
    centers: 1,
    population: '180,000',
    landmark: 'Greater Providence',
    releaseDate: '2026-09-01',
  },
  {
    slug: 'manchester-nh-tesla-service',
    city: 'Manchester',
    state: 'New Hampshire',
    stateAbbr: 'NH',
    waitWeeks: '3–5',
    centers: 1,
    population: '115,000',
    landmark: 'Southern New Hampshire',
    releaseDate: '2026-10-15',
  },
  {
    slug: 'portland-me-tesla-service',
    city: 'Portland',
    state: 'Maine',
    stateAbbr: 'ME',
    waitWeeks: '3–6',
    centers: 1,
    population: '68,000',
    landmark: 'Greater Portland ME',
    releaseDate: '2026-10-15',
  },
  {
    slug: 'burlington-vt-tesla-service',
    city: 'Burlington',
    state: 'Vermont',
    stateAbbr: 'VT',
    waitWeeks: '4–7',
    centers: 1,
    population: '45,000',
    landmark: 'Chittenden County',
    releaseDate: '2026-10-15',
  },
  {
    slug: 'albany-ny-tesla-service',
    city: 'Albany',
    state: 'New York',
    stateAbbr: 'NY',
    waitWeeks: '4–6',
    centers: 1,
    population: '100,000',
    landmark: 'Capital Region NY',
    releaseDate: '2026-09-01',
  },
  {
    slug: 'buffalo-ny-tesla-service',
    city: 'Buffalo',
    state: 'New York',
    stateAbbr: 'NY',
    waitWeeks: '4–6',
    centers: 1,
    population: '270,000',
    landmark: 'Western New York',
    releaseDate: '2026-09-01',
  },
  {
    slug: 'rochester-ny-tesla-service',
    city: 'Rochester',
    state: 'New York',
    stateAbbr: 'NY',
    waitWeeks: '3–6',
    centers: 1,
    population: '210,000',
    landmark: 'Finger Lakes region',
    releaseDate: '2026-09-01',
  },
  {
    slug: 'pittsburgh-pa-tesla-service',
    city: 'Pittsburgh',
    state: 'Pennsylvania',
    stateAbbr: 'PA',
    waitWeeks: '3–5',
    centers: 1,
    population: '300,000',
    landmark: 'Greater Pittsburgh',
    releaseDate: '2026-09-01',
  },
  {
    slug: 'allentown-pa-tesla-service',
    city: 'Allentown',
    state: 'Pennsylvania',
    stateAbbr: 'PA',
    waitWeeks: '3–5',
    centers: 1,
    population: '125,000',
    landmark: 'Lehigh Valley',
    releaseDate: '2026-09-01',
  },
  {
    slug: 'reading-pa-tesla-service',
    city: 'Reading',
    state: 'Pennsylvania',
    stateAbbr: 'PA',
    waitWeeks: '3–5',
    centers: 1,
    population: '95,000',
    landmark: 'Berks County',
    releaseDate: '2026-11-01',
  },
  {
    slug: 'erie-pa-tesla-service',
    city: 'Erie',
    state: 'Pennsylvania',
    stateAbbr: 'PA',
    waitWeeks: '3–6',
    centers: 1,
    population: '95,000',
    landmark: 'Lake Erie',
    releaseDate: '2026-10-15',
  },
  {
    slug: 'scranton-pa-tesla-service',
    city: 'Scranton',
    state: 'Pennsylvania',
    stateAbbr: 'PA',
    waitWeeks: '3–6',
    centers: 1,
    population: '77,000',
    landmark: 'Northeastern PA',
    releaseDate: '2026-10-15',
  },

  // ── Ohio ─────────────────────────────────────────────────────────────────
  {
    slug: 'cleveland-oh-tesla-service',
    city: 'Cleveland',
    state: 'Ohio',
    stateAbbr: 'OH',
    waitWeeks: '3–5',
    centers: 1,
    population: '370,000',
    landmark: 'Greater Cleveland',
    releaseDate: '2026-09-01',
  },
  {
    slug: 'cincinnati-oh-tesla-service',
    city: 'Cincinnati',
    state: 'Ohio',
    stateAbbr: 'OH',
    waitWeeks: '3–5',
    centers: 1,
    population: '310,000',
    landmark: 'Greater Cincinnati',
    releaseDate: '2026-09-01',
  },
  {
    slug: 'akron-oh-tesla-service',
    city: 'Akron',
    state: 'Ohio',
    stateAbbr: 'OH',
    waitWeeks: '3–5',
    centers: 1,
    population: '190,000',
    landmark: 'Summit County',
    releaseDate: '2026-09-01',
  },
  {
    slug: 'toledo-oh-tesla-service',
    city: 'Toledo',
    state: 'Ohio',
    stateAbbr: 'OH',
    waitWeeks: '3–5',
    centers: 1,
    population: '270,000',
    landmark: 'Northwest Ohio',
    releaseDate: '2026-09-01',
  },
  {
    slug: 'dayton-oh-tesla-service',
    city: 'Dayton',
    state: 'Ohio',
    stateAbbr: 'OH',
    waitWeeks: '3–5',
    centers: 1,
    population: '140,000',
    landmark: 'Greater Dayton',
    releaseDate: '2026-09-01',
  },

  // ── Texas ─────────────────────────────────────────────────────────────────
  {
    slug: 'fort-worth-tx-tesla-service',
    city: 'Fort Worth',
    state: 'Texas',
    stateAbbr: 'TX',
    waitWeeks: '3–5',
    centers: 1,
    population: '920,000',
    landmark: 'DFW Metroplex',
    releaseDate: '2026-09-01',
  },
  {
    slug: 'arlington-tx-tesla-service',
    city: 'Arlington',
    state: 'Texas',
    stateAbbr: 'TX',
    waitWeeks: '3–5',
    centers: 1,
    population: '395,000',
    landmark: 'DFW Metroplex',
    releaseDate: '2026-09-15',
  },
  {
    slug: 'plano-tx-tesla-service',
    city: 'Plano',
    state: 'Texas',
    stateAbbr: 'TX',
    waitWeeks: '3–5',
    centers: 1,
    population: '290,000',
    landmark: 'North Dallas',
    releaseDate: '2026-09-01',
  },
  {
    slug: 'garland-tx-tesla-service',
    city: 'Garland',
    state: 'Texas',
    stateAbbr: 'TX',
    waitWeeks: '3–5',
    centers: 1,
    population: '240,000',
    landmark: 'DFW Metroplex',
    releaseDate: '2026-09-01',
  },
  {
    slug: 'irving-tx-tesla-service',
    city: 'Irving',
    state: 'Texas',
    stateAbbr: 'TX',
    waitWeeks: '3–5',
    centers: 1,
    population: '240,000',
    landmark: 'DFW Metroplex',
    releaseDate: '2026-09-01',
  },
  {
    slug: 'mcallen-tx-tesla-service',
    city: 'McAllen',
    state: 'Texas',
    stateAbbr: 'TX',
    waitWeeks: '2–4',
    centers: 1,
    population: '145,000',
    landmark: 'Rio Grande Valley',
    releaseDate: '2026-09-15',
  },
  {
    slug: 'el-paso-tx-tesla-service',
    city: 'El Paso',
    state: 'Texas',
    stateAbbr: 'TX',
    waitWeeks: '2–4',
    centers: 1,
    population: '680,000',
    landmark: 'Borderland',
    releaseDate: '2026-09-15',
  },
  {
    slug: 'lubbock-tx-tesla-service',
    city: 'Lubbock',
    state: 'Texas',
    stateAbbr: 'TX',
    waitWeeks: '2–4',
    centers: 1,
    population: '260,000',
    landmark: 'South Plains',
    releaseDate: '2026-09-15',
  },

  // ── Florida ───────────────────────────────────────────────────────────────
  {
    slug: 'fort-lauderdale-fl-tesla-service',
    city: 'Fort Lauderdale',
    state: 'Florida',
    stateAbbr: 'FL',
    waitWeeks: '3–6',
    centers: 1,
    population: '185,000',
    landmark: 'Broward County',
    releaseDate: '2026-09-15',
  },
  {
    slug: 'west-palm-beach-fl-tesla-service',
    city: 'West Palm Beach',
    state: 'Florida',
    stateAbbr: 'FL',
    waitWeeks: '3–6',
    centers: 1,
    population: '115,000',
    landmark: 'Palm Beach County',
    releaseDate: '2026-09-15',
  },
  {
    slug: 'jacksonville-fl-tesla-service',
    city: 'Jacksonville',
    state: 'Florida',
    stateAbbr: 'FL',
    waitWeeks: '3–5',
    centers: 1,
    population: '950,000',
    landmark: 'Northeast Florida',
    releaseDate: '2026-09-15',
  },
  {
    slug: 'tallahassee-fl-tesla-service',
    city: 'Tallahassee',
    state: 'Florida',
    stateAbbr: 'FL',
    waitWeeks: '3–6',
    centers: 1,
    population: '195,000',
    landmark: 'North Florida',
    releaseDate: '2026-09-15',
  },
  {
    slug: 'sarasota-fl-tesla-service',
    city: 'Sarasota',
    state: 'Florida',
    stateAbbr: 'FL',
    waitWeeks: '3–5',
    centers: 1,
    population: '57,000',
    landmark: 'Sarasota County',
    releaseDate: '2026-09-15',
  },
  {
    slug: 'cape-coral-fl-tesla-service',
    city: 'Cape Coral',
    state: 'Florida',
    stateAbbr: 'FL',
    waitWeeks: '3–5',
    centers: 1,
    population: '194,000',
    landmark: 'Lee County',
    releaseDate: '2026-09-15',
  },
  {
    slug: 'fort-myers-fl-tesla-service',
    city: 'Fort Myers',
    state: 'Florida',
    stateAbbr: 'FL',
    waitWeeks: '3–5',
    centers: 1,
    population: '87,000',
    landmark: 'Southwest Florida',
    releaseDate: '2026-09-15',
  },
  {
    slug: 'gainesville-fl-tesla-service',
    city: 'Gainesville',
    state: 'Florida',
    stateAbbr: 'FL',
    waitWeeks: '3–5',
    centers: 1,
    population: '140,000',
    landmark: 'North Central Florida',
    releaseDate: '2026-09-15',
  },
  {
    slug: 'pensacola-fl-tesla-service',
    city: 'Pensacola',
    state: 'Florida',
    stateAbbr: 'FL',
    waitWeeks: '3–6',
    centers: 1,
    population: '53,000',
    landmark: 'Florida Panhandle',
    releaseDate: '2026-09-15',
  },

  // ── Carolinas ─────────────────────────────────────────────────────────────
  {
    slug: 'charleston-sc-tesla-service',
    city: 'Charleston',
    state: 'South Carolina',
    stateAbbr: 'SC',
    waitWeeks: '3–6',
    centers: 1,
    population: '150,000',
    landmark: 'Lowcountry',
    releaseDate: '2026-09-15',
  },
  {
    slug: 'columbia-sc-tesla-service',
    city: 'Columbia',
    state: 'South Carolina',
    stateAbbr: 'SC',
    waitWeeks: '3–5',
    centers: 1,
    population: '133,000',
    landmark: 'Midlands SC',
    releaseDate: '2026-09-15',
  },
  {
    slug: 'greenville-sc-tesla-service',
    city: 'Greenville',
    state: 'South Carolina',
    stateAbbr: 'SC',
    waitWeeks: '3–5',
    centers: 1,
    population: '72,000',
    landmark: 'Upstate South Carolina',
    releaseDate: '2026-10-01',
  },
  {
    slug: 'greensboro-nc-tesla-service',
    city: 'Greensboro',
    state: 'North Carolina',
    stateAbbr: 'NC',
    waitWeeks: '3–5',
    centers: 1,
    population: '300,000',
    landmark: 'Piedmont Triad',
    releaseDate: '2026-10-01',
  },
  {
    slug: 'durham-nc-tesla-service',
    city: 'Durham',
    state: 'North Carolina',
    stateAbbr: 'NC',
    waitWeeks: '3–5',
    centers: 1,
    population: '283,000',
    landmark: 'Research Triangle',
    releaseDate: '2026-10-01',
  },
  {
    slug: 'winston-salem-nc-tesla-service',
    city: 'Winston-Salem',
    state: 'North Carolina',
    stateAbbr: 'NC',
    waitWeeks: '3–5',
    centers: 1,
    population: '250,000',
    landmark: 'Piedmont Triad',
    releaseDate: '2026-10-01',
  },
  {
    slug: 'fayetteville-nc-tesla-service',
    city: 'Fayetteville',
    state: 'North Carolina',
    stateAbbr: 'NC',
    waitWeeks: '3–6',
    centers: 1,
    population: '208,000',
    landmark: 'Sandhills NC',
    releaseDate: '2026-10-01',
  },

  // ── Tennessee / Alabama / Mississippi / Arkansas / Louisiana ──────────────
  {
    slug: 'knoxville-tn-tesla-service',
    city: 'Knoxville',
    state: 'Tennessee',
    stateAbbr: 'TN',
    waitWeeks: '3–5',
    centers: 1,
    population: '190,000',
    landmark: 'East Tennessee',
    releaseDate: '2026-10-01',
  },
  {
    slug: 'chattanooga-tn-tesla-service',
    city: 'Chattanooga',
    state: 'Tennessee',
    stateAbbr: 'TN',
    waitWeeks: '3–5',
    centers: 1,
    population: '180,000',
    landmark: 'Tennessee Valley',
    releaseDate: '2026-10-01',
  },
  {
    slug: 'clarksville-tn-tesla-service',
    city: 'Clarksville',
    state: 'Tennessee',
    stateAbbr: 'TN',
    waitWeeks: '3–5',
    centers: 1,
    population: '170,000',
    landmark: 'Middle Tennessee',
    releaseDate: '2026-10-01',
  },
  {
    slug: 'birmingham-al-tesla-service',
    city: 'Birmingham',
    state: 'Alabama',
    stateAbbr: 'AL',
    waitWeeks: '3–6',
    centers: 1,
    population: '212,000',
    landmark: 'Greater Birmingham',
    releaseDate: '2026-10-01',
  },
  {
    slug: 'montgomery-al-tesla-service',
    city: 'Montgomery',
    state: 'Alabama',
    stateAbbr: 'AL',
    waitWeeks: '3–6',
    centers: 1,
    population: '200,000',
    landmark: 'Central Alabama',
    releaseDate: '2026-10-01',
  },
  {
    slug: 'huntsville-al-tesla-service',
    city: 'Huntsville',
    state: 'Alabama',
    stateAbbr: 'AL',
    waitWeeks: '2–4',
    centers: 1,
    population: '215,000',
    landmark: 'Tennessee Valley AL',
    releaseDate: '2026-10-01',
  },
  {
    slug: 'mobile-al-tesla-service',
    city: 'Mobile',
    state: 'Alabama',
    stateAbbr: 'AL',
    waitWeeks: '3–6',
    centers: 1,
    population: '187,000',
    landmark: 'Gulf Coast Alabama',
    releaseDate: '2026-10-01',
  },
  {
    slug: 'jackson-ms-tesla-service',
    city: 'Jackson',
    state: 'Mississippi',
    stateAbbr: 'MS',
    waitWeeks: '3–6',
    centers: 1,
    population: '153,000',
    landmark: 'Central Mississippi',
    releaseDate: '2026-10-01',
  },
  {
    slug: 'little-rock-ar-tesla-service',
    city: 'Little Rock',
    state: 'Arkansas',
    stateAbbr: 'AR',
    waitWeeks: '3–5',
    centers: 1,
    population: '202,000',
    landmark: 'Central Arkansas',
    releaseDate: '2026-10-01',
  },
  {
    slug: 'shreveport-la-tesla-service',
    city: 'Shreveport',
    state: 'Louisiana',
    stateAbbr: 'LA',
    waitWeeks: '3–6',
    centers: 1,
    population: '187,000',
    landmark: 'Northwest Louisiana',
    releaseDate: '2026-10-01',
  },
  {
    slug: 'baton-rouge-la-tesla-service',
    city: 'Baton Rouge',
    state: 'Louisiana',
    stateAbbr: 'LA',
    waitWeeks: '3–6',
    centers: 1,
    population: '228,000',
    landmark: 'Capital Region LA',
    releaseDate: '2026-10-15',
  },
  {
    slug: 'lafayette-la-tesla-service',
    city: 'Lafayette',
    state: 'Louisiana',
    stateAbbr: 'LA',
    waitWeeks: '3–5',
    centers: 1,
    population: '122,000',
    landmark: 'Acadiana',
    releaseDate: '2026-10-15',
  },

  // ── Great Plains / Midwest ────────────────────────────────────────────────
  {
    slug: 'wichita-ks-tesla-service',
    city: 'Wichita',
    state: 'Kansas',
    stateAbbr: 'KS',
    waitWeeks: '2–4',
    centers: 1,
    population: '395,000',
    landmark: 'South Central Kansas',
    releaseDate: '2026-10-15',
  },
  {
    slug: 'topeka-ks-tesla-service',
    city: 'Topeka',
    state: 'Kansas',
    stateAbbr: 'KS',
    waitWeeks: '2–4',
    centers: 1,
    population: '126,000',
    landmark: 'Northeast Kansas',
    releaseDate: '2026-10-15',
  },
  {
    slug: 'omaha-ne-tesla-service',
    city: 'Omaha',
    state: 'Nebraska',
    stateAbbr: 'NE',
    waitWeeks: '2–4',
    centers: 1,
    population: '480,000',
    landmark: 'Greater Omaha',
    releaseDate: '2026-10-15',
  },
  {
    slug: 'lincoln-ne-tesla-service',
    city: 'Lincoln',
    state: 'Nebraska',
    stateAbbr: 'NE',
    waitWeeks: '2–4',
    centers: 1,
    population: '295,000',
    landmark: 'Southeast Nebraska',
    releaseDate: '2026-10-15',
  },
  {
    slug: 'sioux-falls-sd-tesla-service',
    city: 'Sioux Falls',
    state: 'South Dakota',
    stateAbbr: 'SD',
    waitWeeks: '2–4',
    centers: 1,
    population: '196,000',
    landmark: 'Eastern South Dakota',
    releaseDate: '2026-10-15',
  },
  {
    slug: 'fargo-nd-tesla-service',
    city: 'Fargo',
    state: 'North Dakota',
    stateAbbr: 'ND',
    waitWeeks: '2–4',
    centers: 1,
    population: '125,000',
    landmark: 'Red River Valley',
    releaseDate: '2026-10-15',
  },
  {
    slug: 'bismarck-nd-tesla-service',
    city: 'Bismarck',
    state: 'North Dakota',
    stateAbbr: 'ND',
    waitWeeks: '2–4',
    centers: 1,
    population: '73,000',
    landmark: 'South-central ND',
    releaseDate: '2026-10-15',
  },

  // ── Mountain West ─────────────────────────────────────────────────────────
  {
    slug: 'billings-mt-tesla-service',
    city: 'Billings',
    state: 'Montana',
    stateAbbr: 'MT',
    waitWeeks: '2–5',
    centers: 1,
    population: '118,000',
    landmark: 'Yellowstone Valley',
    releaseDate: '2026-10-15',
  },
  {
    slug: 'missoula-mt-tesla-service',
    city: 'Missoula',
    state: 'Montana',
    stateAbbr: 'MT',
    waitWeeks: '2–5',
    centers: 1,
    population: '75,000',
    landmark: 'Western Montana',
    releaseDate: '2026-10-15',
  },
  {
    slug: 'great-falls-mt-tesla-service',
    city: 'Great Falls',
    state: 'Montana',
    stateAbbr: 'MT',
    waitWeeks: '2–5',
    centers: 1,
    population: '60,000',
    landmark: 'North-central Montana',
    releaseDate: '2026-10-15',
  },
  {
    slug: 'casper-wy-tesla-service',
    city: 'Casper',
    state: 'Wyoming',
    stateAbbr: 'WY',
    waitWeeks: '2–5',
    centers: 1,
    population: '59,000',
    landmark: 'Central Wyoming',
    releaseDate: '2026-10-15',
  },
  {
    slug: 'cheyenne-wy-tesla-service',
    city: 'Cheyenne',
    state: 'Wyoming',
    stateAbbr: 'WY',
    waitWeeks: '2–5',
    centers: 1,
    population: '64,000',
    landmark: 'High Plains',
    releaseDate: '2026-10-15',
  },
  {
    slug: 'rapid-city-sd-tesla-service',
    city: 'Rapid City',
    state: 'South Dakota',
    stateAbbr: 'SD',
    waitWeeks: '2–5',
    centers: 1,
    population: '78,000',
    landmark: 'Black Hills',
    releaseDate: '2026-10-15',
  },

  // ── Pacific / Hawaii / Alaska ─────────────────────────────────────────────
  {
    slug: 'anchorage-ak-tesla-service',
    city: 'Anchorage',
    state: 'Alaska',
    stateAbbr: 'AK',
    waitWeeks: '4–8',
    centers: 1,
    population: '290,000',
    landmark: 'Southcentral Alaska',
    releaseDate: '2026-10-15',
  },
  {
    slug: 'honolulu-hi-tesla-service',
    city: 'Honolulu',
    state: 'Hawaii',
    stateAbbr: 'HI',
    waitWeeks: '4–8',
    centers: 1,
    population: '350,000',
    landmark: 'Oahu',
    releaseDate: '2026-10-15',
  },
  {
    slug: 'maui-hi-tesla-service',
    city: 'Maui',
    state: 'Hawaii',
    stateAbbr: 'HI',
    waitWeeks: '5–10',
    centers: 1,
    population: '165,000',
    landmark: 'Valley Isle',
    releaseDate: '2026-10-15',
  },
]

export const centerBySlug = new Map(SERVICE_CENTERS.map((c) => [c.slug, c]))
